version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.1

workflows:
  build:
    jobs:
      - cypress/install:
        build: "npm run build"
   - cypress/run:
        record: true
        parallel: true
        parallelism: 10